namespace LiveSplit.AsrInterop.SourceGenerators.AutosplitterSettings;

internal static class Sources
{
    public const string Implementation = $$"""
        // <auto-generated />

        namespace {{Tokens.TypeNamespace}} {
            partial class {{Tokens.TypeName}} {
                public partial void RegisterSettings() {
                    {{Tokens.SettingsRegistration}}
                }

                {{Tokens.SettingsImplementation}}
            }
        }
        """;

    public const string ImplementationWithInterface = $$"""
        // <auto-generated />

        namespace {{Tokens.TypeNamespace}} {
            partial class {{Tokens.TypeName}} : {{Names.AutosplitterSettingsInterface}} {
                public LiveSplit.AsrInterop.Core.SettingsMap Map { get; set; }

                public void RegisterSettings() {
                    {{Tokens.SettingsRegistration}}
                }

                {{Tokens.SettingsImplementation}}
            }
        }
        """;

    public const string ImplementationGlobalNamespace = $$"""
        // <auto-generated />

        partial class {{Tokens.TypeName}} {
            public partial void RegisterSettings() {
                {{Tokens.SettingsRegistration}}
            }

            {{Tokens.SettingsImplementation}}
        }
        """;

    public const string ImplementationGlobalNamespaceWithInterface = $$"""
        // <auto-generated />

        partial class {{Tokens.TypeName}} : {{Names.AutosplitterSettingsInterface}} {
            public LiveSplit.AsrInterop.Core.SettingsMap Map { get; set; }

            public void RegisterSettings() {
                {{Tokens.SettingsRegistration}}
            }

            {{Tokens.SettingsImplementation}}
        }
        """;
}
