namespace LiveSplit.AsrInterop.SourceGenerators;

public static class Sources
{
    public const string AutosplitterExports = $$"""
        // <auto-generated />

        #nullable enable

        file class AutosplitterExports {
            public static LiveSplit.AsrInterop.Autosplitter Splitter { get; } = new {{Tokens.TypeFullName}}();
            public static LiveSplit.AsrInterop.ExternalProcess? Game { get; set; }

            static AutosplitterExports() {
                Splitter.Startup();
            }

            [global::System.Diagnostics.StackTraceHiddenAttribute]
            [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = "update")]
            private static void UpdateInternal() {
                Splitter.Map = LiveSplit.AsrInterop.Core.SettingsMap.Load();

                if (Game is null) {
                    foreach (string processName in Splitter.ProcessNames) {
                        if (LiveSplit.AsrInterop.Process.TryGetProcessByName(processName, out LiveSplit.AsrInterop.ExternalProcess? game)
                            && Splitter.Init(game)) {
                            Game = process;
                            break;
                        }
                    }

                    if (Game is null) {
                        return;
                    }
                }

                if (Game.HasExited) {
                    Game.Dispose();
                    Game = null;

                    Splitter.Exit();

                    return;
                }

                if (!Splitter.Update(Game)) {
                    return;
                }

                switch (LiveSplit.AsrInterop.Core.Timer.GetState()) {
                    case LiveSplit.AsrInterop.Core.TimerState.NotRunning:
                        if (Splitter.Start(Game)) {
                            LiveSplit.AsrInterop.Core.Timer.Start();
                            goto case LiveSplit.AsrInterop.Core.TimerState.Running;
                        }
                        break;

                    case LiveSplit.AsrInterop.Core.TimerState.Running:
                    case LiveSplit.AsrInterop.Core.TimerState.Paused:
                        if (Splitter.IsLoading(Game)) {
                            LiveSplit.AsrInterop.Core.Timer.PauseGameTime();
                        }
                        else {
                            LiveSplit.AsrInterop.Core.Timer.ResumeGameTime();
                        }

                        if (Splitter.GameTime(Game) is global::System.TimeSpan gameTime) {
                            LiveSplit.AsrInterop.Core.Timer.SetGameTime(gameTime.Seconds, gameTime.Nanoseconds);
                        }

                        if (Splitter.Reset(Game)) {
                            LiveSplit.AsrInterop.Core.Timer.Reset();
                        }
                        else if (Splitter.Split(Game)) {
                            LiveSplit.AsrInterop.Core.Timer.Split();
                        }
                        break;
                }
            }
        }
        """;

    public const string SettingsImplementation = $$"""
        // <auto-generated />

        namespace {{Tokens.TypeNamespace}} {
            partial class {{Tokens.TypeName}} : LiveSplit.AsrInterop.IAutosplitterSettings {
                public void RegisterSettings() {
                    {{Tokens.SettingsRegistration}}
                }

                {{Tokens.SettingsImplementation}}
            }
        }
        """;

    public const string SettingsImplementationNoInterface = $$"""
        // <auto-generated />

        namespace {{Tokens.TypeNamespace}} {
            partial class {{Tokens.TypeName}} {
                public partial void RegisterSettings() {
                    {{Tokens.SettingsRegistration}}
                }

                {{Tokens.SettingsImplementation}}
            }
        }
        """;

    public const string SettingsImplementationGlobalNamespace = $$"""
        // <auto-generated />

        partial class {{Tokens.TypeName}} : LiveSplit.AsrInterop.IAutosplitterSettings {
            public void RegisterSettings() {
                {{Tokens.SettingsRegistration}}
            }

            {{Tokens.SettingsImplementation}}
        }
        """;

    public const string SettingsImplementationGlobalNamespaceNoInterface = $$"""
        // <auto-generated />

        partial class {{Tokens.TypeName}} {
            public partial void RegisterSettings() {
                {{Tokens.SettingsRegistration}}
            }

            {{Tokens.SettingsImplementation}}
        }
        """;
}
