using System.Text;
using System.Threading.Tasks;

using LiveSplit.AsrInterop.SourceGenerators.AutosplitterSettings;

using Microsoft.CodeAnalysis.Text;

using Xunit;

using VerifyCs = LiveSplit.AsrInterop.SourceGenerators.UnitTests.CSharpIncrementalGeneratorVerifier<
    LiveSplit.AsrInterop.SourceGenerators.AutosplitterSettings.AutosplitterSettingsGenerator>;

namespace LiveSplit.AsrInterop.SourceGenerators.UnitTests;

public sealed class SettingsGeneratorTests
{
    [Fact]
    public async Task Should_Generate_Settings()
    {
        string @class = "TestSettings";
        string @namespace = "SettingsTests";
        string fullName = $"{@namespace}.{@class}";

        string source = $$"""
            namespace {{@namespace}};

            [{{AutosplitterSettingsGenerator.AttributeMetadataName}}]
            public partial class {{@class}}
            {
                [{{AutosplitterSettings.Names.ToggleAttribute}}("key")]
                public partial bool TestToggle { get; }
            }
            """;

        string expected = $$"""
            // <auto-generated />

            namespace {{@namespace}} {
                partial class {{@class}} : {{AutosplitterSettings.Names.AutosplitterSettingsInterface}} {
                    public LiveSplit.AsrInterop.Core.SettingsMap Map { get; set; }

                    public void RegisterSettings() {
                        {{AutosplitterSettings.Names.UserSettings}}.AddBool(key: "key", description: "key", defaultValue: false);

                    }

                    public partial bool TestToggle => (({{AutosplitterSettings.Names.AutosplitterSettingsInterface}})this).GetToggle(key: "key");

                }
            }
            """;

        await new VerifyCs.Test
        {
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (
                        typeof(AutosplitterSettingsGenerator),
                        $"{fullName}.Impl.g.cs",
                        SourceText.From(expected, Encoding.UTF8, SourceHashAlgorithm.Sha256)
                    )
                }
            }
        }.RunAsync();
    }
}
